# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Code formatters
spotless_version=8.1.0
palantir_java_format_version=2.85.0

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.18.6
loom_version=1.15-SNAPSHOT
publish_plugin_version=1.1.0

# Mod Properties
mod_version=2.0.0
maven_group=dev.gga.techextensions
archives_base_name=techextensions

# Dependencies
fabric_api_version=0.145.4+26.1.2
tech_reborn_version=26.1:6.0.3
