name: release
on:
  workflow_dispatch:
    inputs:
      channel:
        description: Release channel
        required: true
        type: choice
        options:
          - stable
          - beta
          - alpha
        default: stable

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "microsoft"
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: changelog
        uses: FabricMC/fabric-action-scripts@v2
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - name: run datagen
        run: ./gradlew runDatagen
      - name: build
        run: ./gradlew build
      - name: publish
        run: ./gradlew publishMods
        env:
          RELEASE_CHANNEL: ${{ github.event.inputs.channel }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
